aws_account_id = "651146012268"
aws_region = "eu-west-1"
otf_state_s3_bucket_name = "julmosport-web-otf-prod-euwest1-s3"
otf_state_s3_file_name = "julmosport-web/terraform.tfstate"
github_repository = "spacetimewave/julmosport-web"
github_repository_branch = "main"